#! /bin/sh

sxhkd &
hsetroot -solid "#667899" &
picom -b &
xsetroot -cursor_name left_ptr &
/usr/libexec/xfce-polkit &
conky -b &
xob-start &
lock &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         0
bspc config window_gap           7

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a mpv state=floating
bspc rule -a Blender desktop='^7' state=fullscreen follow=on
bspc rule -a krita desktop='^6' state=fullscreen follow=on
